<?php
 function fetch_data()
 {

      $output = '';
      include('connect.php');
      $sql="SELECT * FROM user order by Name";
      $result=mysqli_query($conn,$sql);
      while($row=mysqli_fetch_array($result)){
        $id=$row['ID'];
        $RFID=$row['RFID'];
        $Name = $row['Name'];
        $Batch = $row['Batch'];
        $Course = $row['Course'];
        $Phone_Number = $row['Phone_Number'];
        $Email = $row['Email'];
        $sql="SELECT * FROM librarydata where ID='$id' order by Enrty_Time";
        $res=mysqli_query($conn,$sql);
        if(mysqli_num_rows($res)>0){
        while($dd=mysqli_fetch_array($res)){
        $entry=$dd['Enrty_Time'];
        $exit=$dd['Exit_time'];


      {
      $output .= '<tr>
                          <td>'.$id.'</td>
                          <td>'.$RFID.'</td>
                          <td>'.$Name.'</td>
                          <td>'.$Batch.'</td>
                          <td>'.$Course.'</td>
                          <td>'.$Phone_Number.'</td>
                          <td>'.$Email.'</td>
                          <td>'.$entry.'</td>
                          <td>'.$exit.'</td>

                     </tr>
                          ';
      }}}}
  return $output;
 }
 if(isset($_POST["create_pdf"]))
 {
      require_once('tcpdf/tcpdf.php');
      $obj_pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
      $obj_pdf->SetCreator(PDF_CREATOR);
      $obj_pdf->SetTitle("Library Register Log");
      $obj_pdf->SetHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);
      $obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
      $obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
      $obj_pdf->SetDefaultMonospacedFont('helvetica');
      $obj_pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
      $obj_pdf->SetMargins(PDF_MARGIN_LEFT, '5', PDF_MARGIN_RIGHT);
      $obj_pdf->setPrintHeader(false);
      $obj_pdf->setPrintFooter(false);
      $obj_pdf->SetAutoPageBreak(TRUE, 10);
      $obj_pdf->SetFont('helvetica', '', 6);
      $obj_pdf->AddPage();
      $content = '';
      $content .= '
      <h3 align="center"><BR>
Library Register Log<br><br><br><br>


      <table border="1" cellspacing="0" cellpadding="5">
           <tr>
           <td>ID</td>
           <td>NAME</td>
           <td>BATCH</td>
           <td>COURSE</td>
           <td>Department</td>
           <td>Phone Number</td>
           <td>Email</td>

           <td>Entry Time</td>
           <td>Exit Time</td>

           </tr>
      ';
      $content .= fetch_data();
      $content .= '</table><BR><HR>

      <p style="font-size:7px;">AUTOGENERATED BY COMPUTER</P>';
      $obj_pdf->writeHTML($content);
      $obj_pdf->Output('Library_Register_Log.pdf', 'I');
 }
 ?>
 <?php session_start();?>
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta name="description" content="">
     <meta name="author" content="">
     <link href="css/bootstrap.css" rel="stylesheet">
     <link href="css/jssss.css" rel="stylesheet">
     <link href="css/font-awesome.min.css" rel="stylesheet">
     <link href="css/animate.min.css" rel="stylesheet">
     <link href="css/prettyPhoto.css" rel="stylesheet">
     <link href="css/main3.css" rel="stylesheet">
     <link href="css/responsive.css" rel="stylesheet">
     <link rel="stylesheet" href="style.css" />
     <link rel="stylesheet" href="lightslider.css">
     <script type="text/javascript" src="jquery.js"></script>
     <script type="text/javascript" src="lightslider.js"></script>
 <style>
 .cards1{
 min-width: 20%;
 min-height:20%;
 background-color: black;
 border-radius: 5px;
 display: inline-block;
 margin:10px;

 }
 .cards1:hover{
   box-shadow:2px 2px 10px black;
 }
 .image1 img{
 width:100%;
 border-radius: 50px;
 }
 .title1{
   text-align: center;
   padding: 50px;
 }
 .jj{
   padding-top: 100px;
   }
   .connect{
   padding-left:200px;
   padding-right:200px;

   }</style>
   <link rel="stylesheet" type="text/css" href="text9.css">
   <link rel="stylesheet" type="text/css" href="style.css">
   <link rel="stylesheet" type="text/css" href="img3.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <style>
   #here{
     opacity: 0;
     filter: alpha(opacity=0);
   }
   #subHere{
     opacity: 0;
     filter: alpha(opacity=0);
   }
   </style>
   </head><!--/head-->

   <!--*********************************************START OF NAVIGATION BAR****************************************-->
   <body>
     <nav class="navbar navbar-inverse" role="banner">
           <div class="container">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                       <span class="sr-only">Toggle navigation</span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                    <a href="index.php"><h2 class="wow fadeInDown" style="margin-top:20px;padding-left:0px; color:#FFF;">
                 <center>Library Gate Way</center></h2><h2 class="wow fadeInDown" style="margin-top:-10px;padding-left:0px; color:#FFF;">

               </h2></a>
               </div>



               <div class="collapse navbar-collapse navbar-right wow fadeInDown">
                   <ul class="nav navbar-nav">
                        <li class="active"><a href="index.php"><i class="fa fa-home"></i>HOME</a></li>



                       <li><a href="logout.php">lOGOUT</a></li>
                   </ul>
               </div>
             </div>
           </nav>
           <div class="connect" style="">
             <form method="GET" enctype="multipart/form-data">
               <br><br>
               <b>Department :</b>
                <select name="cata" >
                  <?php include('connect.php');
                    $sql = "SELECT DISTINCT Department FROM user";
                    $result=mysqli_query($conn, $sql);
                      while($row = mysqli_fetch_assoc($result)){
                        echo '  <option value="'.$row['Department'].'">'.$row['Department'].'</option>';

                      } ?>
                    </select>
                    <input type="date" name="dated" placeholder="Enter Date">


                    <input type="submit" name="save">
                </form>
           <br><br><br><br><center><p style="color:red;font-size:30px;"><b>USER DETAILS</b></p></center>
           <br><br>

           <table border="1" id="userTable">
             <tr>
                       <td width="5%">ID</td>
                       <td width="10%">RFID</td>
                       <td width="15%">Name</td>
                       <td width="10%">Batch</td>
                       <td width="10%">Course</td>
                       <td width="10%">Department</td>

                       <td width="20%">Phone_Number</td>
                       <td width="10%">Email</td>
                       <td width="10%">Entry_Time</td>
                       <td width="10%">Exit_Time</td>


             </tr>

             <?php include('connect.php');
             if(isset($_GET['dated'])){
               $dated=$_GET['dated'];
               $dated .=" 00:00:00";

               $datend=$_GET['dated'];
               $datend .=" 23:59:59";

            }
             if(isset($_GET['cata'])){
               $cata=$_GET['cata'];
               $sql="SELECT * FROM user where Department='$cata'";
             }else {
               $sql="SELECT * FROM user order by Name";
             }
             $result=mysqli_query($conn,$sql);
             while($row=mysqli_fetch_array($result)){
               $id=$row['ID'];
               $RFID=$row['RFID'];
               $Name = $row['Name'];
               $Batch = $row['Batch'];
               $Course = $row['Course'];
               $dept=$row['Department'];
               $Phone_Number = $row['Phone_Number'];
               $Email = $row['Email'];
               if(isset($_GET['dated'])){
                 $sql="SELECT * FROM librarydata where Enrty_time between $dated AND $datend and ID='$id'";

              }else{
               $sql="SELECT * FROM librarydata where ID='$id'  ";
              }
               $res=mysqli_query($conn,$sql);
               if(mysqli_num_rows($res)>0){
               while($dd=mysqli_fetch_array($res)){
               $entry=$dd['Enrty_Time'];
               $exit=$dd['Exit_time'];
             ?>

               <?php if($entry!=''){?>  <tr>
                   <td><?php echo $id; ?></td>
                   <td><?php echo $RFID; ?></td>
                   <td><?php echo $Name; ?></td>
                   <td><?php echo $Batch; ?></td>
                   <td><?php echo $Course; ?></td>
                   <td><?php echo $dept; ?></td>
                   <td><?php echo $Phone_Number; ?></td>
                   <td><?php echo $Email; ?></td>

                   <td><?php echo $entry; ?></td>
                   <td><?php echo $exit; ?></td>


                 </tr>
               <?php }}}} ?>

               </table>




 <br><br>
</div><center>
<form action="" method="POST">
<button type="submit" class="btn btn-success  wow fadeInDown" name="create_pdf"  type="submit" /> Get Report</button>
</form></center><br><br><br><br>
<footer id="footer" class="midnight-blue wow fadeInDown">
         <?php include('footer.php');?>
     </footer><!--/#footer-->
 </body>

 </html>
