<?php
 function fetch_data()
 {

      $output = '';
         include('connect.php');
         $sql = "select * from user  where role='student' order by id desc ";
         $sno = 1;
         $retrieve_data = mysqli_query($conn,$sql);
         while($row = mysqli_fetch_array($retrieve_data)){
             $ID = $row['ID'];
             $RFID = $row['RFID'];
             $Name = $row['Name'];
             $Batch = $row['Batch'];
             $Course = $row['Course'];
             $Department = $row['Department'];
             $Phone_Number = $row['Phone_Number'];
             $Email = $row['Email'];



      {
      $output .= '<tr>
                          <td>'.$ID.'</td>
                          <td>'.$RFID.'</td>
                          <td>'.$Name.'</td>
                          <td>'.$Batch.'</td>
                          <td>'.$Course.'</td>
                          <td>'.$Department.'</td>
                          <td>'.$Phone_Number.'</td>
                          <td>'.$Email.'</td>


                     </tr>
                          ';
      }}
  return $output;
 }
 if(isset($_POST["create_pdf"]))
 {
      require_once('tcpdf/tcpdf.php');
      $obj_pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
      $obj_pdf->SetCreator(PDF_CREATOR);
      $obj_pdf->SetTitle("User Details");
      $obj_pdf->SetHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);
      $obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
      $obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
      $obj_pdf->SetDefaultMonospacedFont('helvetica');
      $obj_pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
      $obj_pdf->SetMargins(PDF_MARGIN_LEFT, '5', PDF_MARGIN_RIGHT);
      $obj_pdf->setPrintHeader(false);
      $obj_pdf->setPrintFooter(false);
      $obj_pdf->SetAutoPageBreak(TRUE, 10);
      $obj_pdf->SetFont('helvetica', '', 6);
      $obj_pdf->AddPage();
      $content = '';
      $content .= '
      <h3 align="center"><BR>
User Details<br><br><br><br>


      <table border="1" cellspacing="0" cellpadding="5">
           <tr>
           <td>ID</td>
           <td>RFID</td>
           <td>Name</td>
           <td>Batch</td>
           <td>Course</td>
           <td>Department</td>
           <td>Phone_Number</td>
           <td>Email</td>
           </tr>
      ';
      $content .= fetch_data();
      $content .= '</table><BR><HR>

      <p style="font-size:7px;">AUTOGENERATED BY COMPUTER</P>';
      $obj_pdf->writeHTML($content);
      $obj_pdf->Output('User_Details.pdf', 'I');
 }
 ?>
 <?php session_start();?>
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta name="description" content="">
     <meta name="author" content="">
     <link href="css/bootstrap.css" rel="stylesheet">
     <link href="css/jssss.css" rel="stylesheet">
     <link href="css/font-awesome.min.css" rel="stylesheet">
     <link href="css/animate.min.css" rel="stylesheet">
     <link href="css/prettyPhoto.css" rel="stylesheet">
     <link href="css/main3.css" rel="stylesheet">
     <link href="css/responsive.css" rel="stylesheet">
     <link rel="stylesheet" href="style.css" />
     <link rel="stylesheet" href="lightslider.css">
     <script type="text/javascript" src="jquery.js"></script>
     <script type="text/javascript" src="lightslider.js"></script>

   <link rel="stylesheet" type="text/css" href="text9.css">
   <link rel="stylesheet" type="text/css" href="style.css">
   <link rel="stylesheet" type="text/css" href="img3.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <style>
   #here{
     opacity: 0;
     filter: alpha(opacity=0);
   }
   #subHere{
     opacity: 0;
     filter: alpha(opacity=0);
   }
   </style>
   </head><!--/head-->

   <!--*********************************************START OF NAVIGATION BAR****************************************-->
   <body>
     <nav class="navbar navbar-inverse" role="banner">
           <div class="container">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                       <span class="sr-only">Toggle navigation</span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                    <a href="index.php"><h2 class="wow fadeInDown" style="margin-top:20px;padding-left:0px; color:#FFF;">
                 <center>Library Gate Way</center></h2><h2 class="wow fadeInDown" style="margin-top:-10px;padding-left:0px; color:#FFF;">

               </h2></a>
               </div>



               <div class="collapse navbar-collapse navbar-right wow fadeInDown">
                   <ul class="nav navbar-nav">
                        <li class="active"><a href="index.php"><i class="fa fa-home"></i>HOME</a></li>

                        <li class="dropdown"><a class="dropdown-toggle wow fadeInDown" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-th"></span> <?php echo $_SESSION['admin']; ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                              <li><a href="useradd.php">ADD USERS</a></li>
                              <li><a href="viewuser.php">VIEW USERS</a></li>
                              <li><a href="edit.php">EDIT USERS</a></li>

                              <li><a href="student1.php">LOG FILE</a></li>
                              </ul>
                        </li>



                       <li><a href="logout.php">lOGOUT</a></li>
                   </ul>
               </div>
             </div>
 </nav><div class="container">
 <br><br><br><br><center><p style="color:red;font-size:30px;"><b>USER DETAILS</b></p></center>
 <br><br>


 <table border="1" id="userTable">
   <tr>
             <td>ID</td>
             <td>RFID</td>
             <td>Name</td>
             <td>Batch</td>
             <td>Course</td>
             <td>Department</td>
             <td>Phone_Number</td>
             <td>Email</td>

   </tr>
   <?php include('connect.php');
     $sql = "select * from user  where role='student' order by id desc ";
     $sno = 1;
     $retrieve_data = mysqli_query($conn,$sql);
     while($row = mysqli_fetch_array($retrieve_data)){
         $ID = $row['ID'];
         $RFID = $row['RFID'];
         $Name = $row['Name'];
         $Batch = $row['Batch'];
         $Course = $row['Course'];
         $Department = $row['Department'];
         $Phone_Number = $row['Phone_Number'];
         $Email = $row['Email'];


         echo "<tr>
         <td>".$ID."</td>
         <td>".$RFID."</td>
         <td>".$Name."</td>
         <td>".$Batch."</td>
         <td>".$Course."</td>
         <td>".$Department."</td>
         <td>".$Phone_Number."</td>
         <td>".$Email."</td>
         </tr>";
         $sno++;
     }
    ?>
 </table>

             <br><br>
 </div><center>
 <form action="" method="POST">
     <button type="submit" class="btn btn-success  wow fadeInDown" name="create_pdf"  type="submit" /> Get Report</button>
</form><br>
<form action="export.php" method="POST">
    <button type="submit" class="btn btn-success  wow fadeInDown" /> Export To XLS</button>
</form>

</center><br><br><br><br>
<footer id="footer" class="midnight-blue wow fadeInDown">
         <?php include('footer.php');?>
     </footer><!--/#footer-->
 </body>

 </html>
